// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func SearchBar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"relative max-w-3xl mx-auto\"><form action=\"/search\" method=\"post\" class=\"border-black border-2 rounded w-full  min-w-96 bg-white p-2 flex justify-between items-center\"><i class=\"fa-solid fa-magnifying-glass text-2xl ml-1\" style=\"color: #000000;\"></i> <input class=\"p-1 w-full rounded peer\" id=\"location\" type=\"search\" name=\"search\" hx-post=\"/api/search/query\" hx-target=\"#location_results\" hx-trigger=\"input changed delayed:500ms, search\" placeholder=\"Search for a City or Suburb\"> <button type=\"submit\" class=\"hover:scale-110 p-2 w-24 h-11 font-bold rounded\" style=\"background-color: #FF8C00;\">Search</button></form><div class=\"absolute max-h-60 overflow-y-scroll w-full bg-white border-black border-2 rounded p-2\"><ul id=\"location_results\"></ul></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
