// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "dwelr/views/layouts"
import "dwelr/models"

func AboutPage(isLoggedIn bool, user models.User) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"py-8 px-14\" style=\"height: calc(100vh - 64px);\"><h1 class=\"text-3xl font-bold mb-4\">Our Story</h1><p>Welcome to Dwelr – where finding or listing a rental property is a breeze. Our journey began with the simple idea of making the rental process more straightforward and stress-free. Discover the story behind Dwelr and how we are reshaping the way people connect with rental homes.</p><div><h2 class=\"text-xl font-bold mb-2 mt-10\">Mission</h2><p>At Dwelr, our mission is to redefine the rental experience. We're dedicated to providing a hassle-free platform where tenants effortlessly discover their ideal homes and landlords connect with the perfect residents. We're committed to transforming the rental journey into an exciting and fulfilling process, making Dwelr the go-to place for seamless connections in the rental market.</p></div><div><h2 class=\"text-xl font-bold mb-2 mt-10\">How it works</h2><p>Navigating Dwelr is easy. Whether you're a tenant searching for the perfect rental or a landlord looking to connect with the right residents, our platform operates on a straightforward process. From listing your property to personalized matches, discover the simplicity of Dwelr.</p></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base(isLoggedIn, user).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
