// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "dwelr/views/layouts"

/* style="height: calc(100vh - 64px);" */

func AddListingPage() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col px-8 w-full max-w-6xl\"><h1 class=\"font-bold text-center text-2xl\">Add Listing Page</h1><div class=\"flex justify-center my-12\"><div class=\"w-1/2 p-4\"><form class=\"flex flex-col\"><label class=\"font-bold mt-5 mb-3 text-base\">Location</label> <input class=\"p-2 border-black border-2 rounded\" type=\"text\" required> <label class=\"font-bold mt-5 mb-3 text-base\">Title</label> <input class=\"p-2 border-black border-2 rounded\" type=\"text\" required> <label class=\"font-bold mt-5 mb-3 text-base\">Description</label> <textarea class=\"p-2 border-black border-2 rounded resize-none\" rows=\"5\" cols=\"50\" required></textarea> <label class=\"font-bold mt-5 mb-3 text-base\">Rental Fee (ZAR)</label> <input class=\"p-2 border-black border-2 rounded\" type=\"number\" min=\"0.00\" max=\"99999.99\" step=\"100.00\" required> <label for=\"type_of_listing\" class=\"font-bold mt-5 mb-3 text-base\">Type of Listing</label> <select name=\"types\" id=\"type_of_listing\" class=\"p-2 border-black border-2 bg-white rounded\"><option value=\"\">-- Select --</option> <option value=\"\">Apartment/Flat</option> <option value=\"\">House</option> <option value=\"\">Room</option></select> <label class=\"font-bold mt-5 mb-3 text-base\">Number of Bedrooms</label> <input class=\"p-2 border-black border-2 rounded\" type=\"number\" min=\"0\" max=\"99\" step=\"1\" required> <label class=\"font-bold mt-5 mb-3 text-base\">Number of Bathrooms</label> <input class=\"p-2 border-black border-2 rounded\" type=\"number\" min=\"0\" max=\"99\" step=\"1\" required></form></div><div class=\"w-1/2 py-4 pr-4 pl-8\"><label class=\"font-bold mt-5 mb-3 text-base block\">Add Photos:</label> <input type=\"file\" accept=\"image/*\"></div></div><button class=\"font-bold w-40 h-14 mx-auto mb-20 rounded\" type=\"submit\" style=\"background-color: #FF8C00;\">Publish Listing</button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
