// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "dwelr/views/components"

func LoginPage() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Dwelr - Login</title><link href=\"/views/css/output.css\" rel=\"stylesheet\"><link href=\"/views/css/styles.css\" rel=\"stylesheet\"><script src=\"https://cdn.tailwindcss.com\"></script><script src=\"https://unpkg.com/htmx.org@1.9.11\" integrity=\"sha384-0gxUXCCR8yv9FM2b+U3FDbsKthCI66oH5IA9fHppQq9DDMHuMauqq1ZHBpJxQ0J0\" crossorigin=\"anonymous\"></script></head><body class=\"\"><div class=\"flex h-screen justify-center items-center\"><div class=\"flex justify-center items-center max-w-4xl rounded shadow-lg\"><div class=\"w-1/2 flex justify-center\"><figure class=\"flex justify-center items-center w-full\"><img class=\"w-full h-full rounded-l\" src=\"views/images/login.png\"></figure></div><div class=\"bg-white w-1/2 flex flex-col justify-center items-center p-6\"><h1 class=\"font-bold text-3xl mb-2\">Welcome!</h1><p class=\"mb-16\">Please enter your details</p><input class=\"bg-white border-b-black border-b-2 px-3 pt-3 p-1 w-80 h-14 placeholder-black\" type=\"email\" name=\"email\" placeholder=\"Email\"> <input class=\"bg-white border-b-black border-b-2 px-3 pt-3 p-1 w-80 h-14 mt-0.5 placeholder-black\" type=\"password\" name=\"password\" placeholder=\"Password\"> <button class=\"bg-black text-white font-bold rounded w-80 h-14 mt-4 \" type=\"submit\" hx-post=\"/login\" hx-target=\"#response\" hx-include=\"[name = &#39;email&#39;], [name = &#39;password&#39;]\">Log In</button><p id=\"response\" class=\"font-lg p-1 mt-10\"></p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
